Hotel/Controllers/TransitionController.cs
using Microsoft.AspNetCore.Mvc;

namespace Hotel.Api.Controllers
{
    public class TransitionController : Controller
    {
        public IActionResult HomePage()
        {
            return View();
        }
        public IActionResult AutorizationPage()
        {
            return View();
        }
        public IActionResult RegisterPage()
        {
            return View();
        }
        public IActionResult QandAPage()
        {
            return View();
        }
        public IActionResult RoomsPage()
        {
            return View();
        }
        public IActionResult MenuPage()
        {
            return View();
        }

        public IActionResult BookingPage()
        {
            return View();
        }

        public IActionResult MyBooking()
        {
            return View();
        }
    }
}

Hotel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Гостиница - Baltic</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="icon" type="image/x-icon" href="Resources//icon.png" />
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a asp-controller="Transition" asp-action="HomePage">Главная</a></li>
                <li><a asp-controller="Transition" asp-action="RoomsPage">Номера</a></li>
                <li><a asp-controller="Transition" asp-action="MenuPage">Меню</a></li>
                <li><a asp-controller="Transition" asp-action="QandAPage">Обратная связь</a></li>
            </ul>
        </nav>
        <div class="unauthorized-actions">
            <form id="registerForm" action="@Url.Action("RegisterPage", "Transition")" method="get" style="display: inline;">
                <button class="registerBtn" type="submit">Регистрация</button>
            </form>
            <form id="authorizationForm" action="@Url.Action("AutorizationPage", "Transition")" method="get" style="display: inline;">
                <button class="authorizationBtn" type="submit">Авторизация</button>
            </form> 
        </div>
        <div class="user-actions">
            <form id="bookingButton" action="@Url.Action("MyBooking", "Transition")" method="get" style="display: inline;">
                <button class="bookingBtn" type="submit">Мои бронирования</button>
            </form>
            <form id="deleteTokenButton" action="@Url.Action("HomePage", "Transition")" method="get" style="display: inline;">
                <button class="exitBtn" type="submit">Выйти</button>
            </form>
        </div>
        <div class="manager-actions">
            <form id="bookingButton" action="@Url.Action("MyBooking", "Transition")" method="get" style="display: inline;">
                <button class="bookingBtn" type="submit">Мои бронирования</button>
            </form>
            <form id="rezervCopyForm" style="display: inline;">
                <button class="rezervCopyBtn" onclick="backupDatabase()">Резервное копирование БД</button>
            </form>
            <form id="deleteTokenButton" action="@Url.Action("HomePage", "Transition")" method="get" style="display: inline;">
                <button class="exitBtn" type="submit">Выйти</button>
            </form>
        </div>
        <div class="admin-actions">
            <form id="bookingButton" action="@Url.Action("MyBooking", "Transition")" method="get" style="display: inline;">
                <button class="bookingBtn" type="submit">Мои бронирования</button>
            </form>
            <form id="adminForm" action="https://localhost:7134/swagger/index.html" style="display: inline;">
                <button class="adminBtn" type="submit">Панель администратора</button>
            </form>
            <form id="rezervCopyForm" style="display: inline;">
                <button class="rezervCopyBtn" onclick="backupDatabase()">Резервное копирование БД</button>
            </form>
            <form id="deleteTokenButton" action="@Url.Action("HomePage", "Transition")" method="get" style="display: inline;">
                <button class="exitBtn" type="submit">Выйти</button>
            </form>
        </div>
    </header>
    <div class="container">
        <div class="preloader">
            <div class="preloader__row">
                <div class="preloader__item"></div>
                <div class="preloader__item"></div>
            </div>
        </div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer>
        <div class="footer-container">
            <div class="social-links">
                <a href="ссылка на Instagram" class="social-icon"><i class="fab fa-vk"></i></a>
                <a href="ссылка на Facebook" class="social-icon"><i class="fab fa-telegram"></i></a>
                <a href="ссылка на Twitter" class="social-icon"><i class="fab fa-whatsapp"></i></a>
            </div>
            <div class="contact-info">
                <p>Телефон: +7-931-363-53-38</p>
                <p>Email: alekskisel5250@gmail.com</p>
            </div>
            <div class="map-container">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d747026.8524690373!2d40.417559246189654!3d42.99778386089476!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x405f2f4f13a442ff%3A0x934852e625989a6f!2z0JDQsdGF0LDQt9C40Y8!5e0!3m2!1sru!2sru!4v1716311903774!5m2!1sru!2sru" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
        </div>
    </footer>
    <script>
        window.onload = function () {
            document.body.classList.add('loaded_hiding');
            window.setTimeout(function () {
                document.body.classList.add('loaded');
                document.body.classList.remove('loaded_hiding');
            }, 500);
        }
    </script>
    <script>
        function backupDatabase() {
            fetch(`https://localhost:7134/BackupDatabase/Copy`, {
                method: "POST"
            })
                .then(response => {
                    if (response.ok) {
                        // Действия после успешного резервного копирования
                        console.log('База данных успешно скопирована');
                    } else {
                        // Обработка ошибки
                        console.error('Ошибка при резервном копировании базы данных');
                    }
                })
                .catch(error => {
                    // Обработка ошибки
                    console.error('Произошла ошибка:', error);
                });
        }

        if (document.readyState === 'complete' || document.readyState === 'interactive') {
            checkToken();
        } else {
            document.addEventListener('DOMContentLoaded', checkToken);
        }

        function checkToken() {
            function getCookie(name) {
                const value = `; ${document.cookie}`;
                const parts = value.split(`; ${name}=`);
                if (parts.length === 2) return parts.pop().split(';').shift();
            }

            const jwtToken = getCookie('jwtToken');
            const userRole = getCookie('userRole');

            if (jwtToken && userRole) {
                const role = parseInt(userRole, 10);
                const unauthorizedElements = document.querySelectorAll('.unauthorized-actions');
                const userElements = document.querySelectorAll('.user-actions');
                const managerElements = document.querySelectorAll('.manager-actions');
                const adminElements = document.querySelectorAll('.admin-actions');

                unauthorizedElements.forEach(function (element) {
                    element.style.display = "none"
                });

                if (role === 0) {
                    // Для обычного пользователя
                    userElements.forEach(function (element) {
                        element.style.display = 'block';
                    });
                    managerElements.forEach(function (element) {
                        element.style.display = 'none';
                    });
                    adminElements.forEach(function (element) {
                        element.style.display = 'none';
                    });
                } else if (role === 1) {
                    // Для администратора
                    adminElements.forEach(function (element) {
                        element.style.display = 'block';
                    });
                    userElements.forEach(function (element) {
                        element.style.display = 'none';
                    });
                    managerElements.forEach(function (element) {
                        element.style.display = 'none';
                    });
                } else if (role === 2) {
                    // Для менеджера
                    managerElements.forEach(function (element) {
                        element.style.display = 'block';
                    });
                    userElements.forEach(function (element) {
                        element.style.display = 'none';
                    });
                    adminElements.forEach(function (element) {
                        element.style.display = 'none';
                    });
                }
            } else {
                // Для неавторизованного пользователя
                console.log("JWT-token или userRole не найден");
                const unauthorizedElements = document.querySelectorAll('.unauthorized-actions');
                unauthorizedElements.forEach(function (element) {
                    element.style.display = "block"
                });
                const userElements = document.querySelectorAll('.user-actions');
                userElements.forEach(function (element) {
                    element.style.display = 'none';
                });
                const managerElements = document.querySelectorAll('.manager-actions');
                managerElements.forEach(function (element) {
                    element.style.display = 'none';
                });
                const adminElements = document.querySelectorAll('.admin-actions');
                adminElements.forEach(function (element) {
                    element.style.display = 'none';
                });
            }
        }

        function deleteJwtToken() {
            // Устанавливаем срок действия cookie в прошлое, чтобы он истек
            document.cookie = "jwtToken=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;";
            // Можно также удалить другие параметры cookie, если они есть
            // document.cookie = "другие_параметры=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;";

            console.log("JWT-токен успешно удален из cookie!");
        }

        // Находим все формы с id "deleteTokenButton"
        const deleteTokenButtons = document.querySelectorAll('#deleteTokenButton');

        // Назначаем обработчик события нажатия на каждую кнопку
        deleteTokenButtons.forEach(button => {
            button.addEventListener('click', deleteJwtToken);
        });
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>